<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
        <LangVersion>latest</LangVersion>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="all" />
    </ItemGroup>
</Project>
