services:
  postgres:
    image: postgres:16-alpine
    container_name: saas_boilerplate_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ChangeMeQuickly1990@
      POSTGRES_DB: saas_db
    volumes:
      - saas_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d saas_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  saas_postgres_data:
